# action.yml
name: 'HugoVerse Release Action'
author: 'MDFriday <me@sunwei.xyz>'
description: 'GitHub Action for building and releasing hugoverse with CGO and libvips support'
branding:
  icon: 'package'
  color: 'blue'

inputs:
  github_token:
    description: 'GitHub token for uploading assets'
    required: true
  goos:
    description: 'Target operating system for the build'
    required: false
    default: 'linux'
  goarch:
    description: 'Target architecture for the build'
    required: false
    default: 'amd64'
  extra_files:
    description: 'Extra files to include in the release archive'
    required: false
    default: 'LICENSE README.md manifest.json'
  version:
    description: 'Version number for the release'
    required: false
    default: ''
  release_repo:
    description: 'Repository to release to (format: owner/repo)'
    required: false
    default: ''

outputs:
  release_asset_dir:
    description: 'Release file directory provided for use by other workflows'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
    INPUT_GOOS: ${{ inputs.goos }}
    INPUT_GOARCH: ${{ inputs.goarch }}
    INPUT_EXTRA_FILES: ${{ inputs.extra_files }}
    VERSION: ${{ inputs.version }}
    GITHUB_REPO: ${{ inputs.release_repo }}
